# Generated by Django 5.1.5 on 2025-02-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relief', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('date_last_seen', models.DateField()),
                ('contact_info', models.CharField(help_text='Enter contact details of informant', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='missing_photos/')),
                ('status', models.CharField(choices=[('Missing', 'Missing'), ('Found', 'Found')], default='Missing', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='name',
            new_name='Fullname',
        ),
        migrations.DeleteModel(
            name='VolunteerAssignment',
        ),
    ]
